### ISSUE TITLE
Error with sdk 4.1.0

### ISSUE THREAD

**Issue by felipe3000** [navinpeiris/jsca2js#18]
Im getting an error with sdk 4.1.0. 

My console output:

Retrieving Titanium JSCA API for version: 4.1.0
Converting API to JavaScript
Traceback (most recent call last):
  File "D:\Users\felipe.almeida-sc\Desktop\jsca2js-master\titanium-mobile.py", l
ine 124, in <module>
    main()
  File "D:\Users\felipe.almeida-sc\Desktop\jsca2js-master\titanium-mobile.py", l
ine 114, in main
    javascript = convertJsca2Js(jsca, version)
  File "D:\Users\felipe.almeida-sc\Desktop\jsca2js-master\jsca2js.py", line 268,
 in convertJsca2Js
    javascript += formatNamespace(namespace)
  File "D:\Users\felipe.almeida-sc\Desktop\jsca2js-master\jsca2js.py", line 251,
 in formatNamespace
    formatter.addLine(formatMethods(namespaceContent))
  File "D:\Users\felipe.almeida-sc\Desktop\jsca2js-master\jsca2js.py", line 196,
 in formatMethods
    formatter.add(generateMethodJSDoc(method))
  File "D:\Users\felipe.almeida-sc\Desktop\jsca2js-master\jsca2js.py", line 142,
 in generateMethodJSDoc
    formatter.addLine(prefix, '@returns ', formatReturn(returns))
  File "D:\Users\felipe.almeida-sc\Desktop\jsca2js-master\formatter.py", line 18
, in addLine
    return self.add(self.indent).add(''.join(args)).newLine()
TypeError: sequence item 2: expected string, list found

**Comment by caspahouzer** [comment]
Same for 5.0.0

**Comment by thiagotalma** [comment]
@navinpeiris please, add 5.0.0 support

**Comment by caspahouzer** [comment]
+1

**Comment by Tako88** [comment]
+1

**Comment by beta-tank** [comment]
I cant convert 5.0.0. too.

**Comment by botmaster** [comment]
+1

**Comment by DeSater** [comment]
Forked and added 5.0.0 support :)

[https://github.com/DeSater/jsca2js](https://github.com/DeSater/jsca2js)
