### ISSUE TITLE
Error with SDK 1.4.0

### ISSUE THREAD

**Issue by stephenconnolly** [navinpeiris/jsca2js#19]
Hello,

See below, I get the the following error:

Retrieving Titanium JSCA API for version: 4.1.0
Converting API to JavaScript
Traceback (most recent call last):
  File "./titanium-mobile.py", line 124, in <module>
    main()
  File "./titanium-mobile.py", line 114, in main
    javascript = convertJsca2Js(jsca, version)
  File "/Users/stephenconnolly/Documents/PhpstormProjects/jsca2js/jsca2js.py", line 268, in convertJsca2Js
    javascript += formatNamespace(namespace)
  File "/Users/stephen/Documents/PhpstormProjects/jsca2js/jsca2js.py", line 251, in formatNamespace
    formatter.addLine(formatMethods(namespaceContent))
  File "/Users/stephen/Documents/PhpstormProjects/jsca2js/jsca2js.py", line 196, in formatMethods
    formatter.add(generateMethodJSDoc(method))
  File "/Users/stephen/Documents/PhpstormProjects/jsca2js/jsca2js.py", line 142, in generateMethodJSDoc
    formatter.addLine(prefix, '@returns ', formatReturn(returns))
  File "/Users/stephen/Documents/PhpstormProjects/jsca2js/formatter.py", line 18, in addLine
    return self.add(self.indent).add(''.join(args)).newLine()
TypeError: sequence item 2: expected string, list found

Any ideas ?

Regards,
Stephen

**Comment by caspahouzer** [comment]
Same for 5.0.0

**Comment by DeSater** [comment]
Forked and added 5.0.0 support :)

[https://github.com/DeSater/jsca2js](https://github.com/DeSater/jsca2js)

**Comment by caspahouzer** [comment]
f**ck yeah!
